name: GitHub Actions Demo
on: [pull_request]
jobs:
  my-first-job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: hello
        run: |
          echo "Hellow world"
        
      - name: run python script
        run: |
           pip install -r requirements.txt 
           python ci.py
