name: GitHub Actions Demo
on: [push]
jobs:
  my-first-job:
    runs-on: macos-latest
    steps:
      - name: hello
        run: |
          echo "Hellow world"
      - name: this will fail
        run: exit 1;
