name: trigger-demo
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  trigger-demo:
    runs-on: macos-latest
    steps:
      - run: echo "Hello"
